dist: bionic
language: php
os: linux

services:
  - mysql

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

addons:
  #firefox: "47.0.1"
  postgresql: "9.6"
  #apt:
  #  packages:
  #    - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2
  - 7.3

env:
  - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
#  - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
#  - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
#  - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
#  - MOODLE_BRANCH=master DB=pgsql
  - MOODLE_BRANCH=master DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - nvm use node
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against one configuration (Moodle, PHP, DB) only.
    - stage: prechecks
      php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
      - moodle-plugin-ci phplint
      #- moodle-plugin-ci phpcpd #disable cpd for now - reports duplicates as failures - would be nice to fix.
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci validate
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      # - moodle-plugin-ci grunt

# Unit tests and behat tests against full matrix (Implicit "test" stage).
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
#  - vendor/bin/phpunit --coverage-clover=coverage.xml

stages:
  - prechecks
  - test

# after_success:
#  - bash <(curl -s https://codecov.io/bash)
