language: php
sudo: false

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

addons:
  #firefox: "47.0.1"
  postgresql: "9.6"
  #apt:
  #  packages:
  #    - oracle-java8-installer
  #    - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.1
#  - 7.2

env:
  global:
    - DB=pgsql
    - DB=mysqli
  matrix:
    - MOODLE_BRANCH=MOODLE_33_STABLE
    - MOODLE_BRANCH=MOODLE_34_STABLE
    - MOODLE_BRANCH=master

matrix:
  include:
    # Test with PHP 7.0
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=master
    # Test with PHP 7.1
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=master
    # Test with PHP 7.2, only 34 and later
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.2
      env: MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9.0
  - nvm use 8.9.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against one configuration (Moodle, PHP, DB) only.
    - stage: prechecks
      php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
      - moodle-plugin-ci phplint
      #- moodle-plugin-ci phpcpd #disable cpd for now - reports duplicates as failures - would be nice to fix.
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci validate
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      # - moodle-plugin-ci grunt

# Unit tests and behat tests against full matrix (Implicit "test" stage).
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
#  - vendor/bin/phpunit --coverage-clover=coverage.xml

stages:
  - prechecks
  - test

# after_success:
#  - bash <(curl -s https://codecov.io/bash)
